data:
    train_data: /opt/ml/data/final_train.csv
    test_data: /opt/ml/data/re_valid.csv
    
model:
    model_name: klue/roberta-small
    saved_model: /opt/ml/saved_model/roberta_small.pt
  
train:
    train_mode: True
    scheduler : CosineAnnealing         # [CosineAnnealing, CyclicLR]
    seed: 42
    batch_size: 16
    epoch: 10
    lr: 1e-5
    logging_step: 1000
    warmup_steps : 500
    weight_decay: 0.01
    eps : 1e-8
    T_0 : 50
    T_mult : 2
    eta_min : 1e-7

wandb:
    project_name: klue-roberta-small  # repo 이름
    exp_name:    # 실험관리로 보여지는 이름
    
test:
    test_mode: False
    output_csv: ~/output_csv/roberta_small.csv